name: Automated tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: defaults,conda-forge,bioconda
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get --assume-yes install wget make procps software-properties-common
        wget -qO- https://get.nextflow.io | bash && sudo cp nextflow /usr/local/bin/nextflow
        conda update --yes conda
    - name: Cache conda environments
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/work/tronflow-bam-preprocessing/tronflow-bam-preprocessing/work/conda
        key: ${{ runner.os }}-tronflow-bam-preprocessing
    - name: Run tests
      run: |
        make